obj-$(CONFIG_HUAWEI_CHARGER_AP) += huawei_charger.o charging_core.o
obj-$(CONFIG_BQ2560X_CHARGER) += bq2560x/
obj-$(CONFIG_RT9466_CHARGER) += rt9466/
obj-$(CONFIG_HL7019_CHARGER) += hl7019/
obj-$(CONFIG_RT9471_CHARGER) += rt9471/
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger/
obj-$(CONFIG_WIRED_CHANNEL_SWITCH) += wired_channel_switch/
obj-$(CONFIG_VBUS_CHANNEL) += vbus_channel/

ccflags-y += -Idrivers/huawei_platform/power/charger/charger_ap
