obj-$(CONFIG_PARADE_TS_KIT) += parade.o
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver

ccflags-y += -Idrivers/devkit/tpkit

ccflags-y += -Idrivers/devkit/tpkit/panel/parade
