# ELAN
obj-$(CONFIG_ELAN_TS_KIT) += elan_ts.o
obj-$(CONFIG_ELAN_TS_KIT) += elan_mmi.o
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver

ccflags-y += -Idrivers/devkit/tpkit

ccflags-y += -Idrivers/devkit/tpkit/panel/elan
