obj-y += ftsCompensation.o
obj-y += ftsCrossCompile.o
obj-y += ftsFrame.o
obj-y += ftsIO.o
obj-y += ftsTest.o
obj-y += ftsTime.o
obj-y += ftsTool.o

ccflags-y += -Idrivers/huawei_platform/touthscreen/panel/st/fts_debug_lib
