obj-$(CONFIG_HISI_DDRC_SEC) += hisi_ddr_secprotect.o

subdir-ccflags-$(CONFIG_HISI_BB) += 	-Idrivers/hisi/mntn/blackbox \
					-I$(srctree)/drivers/hisi/tzdriver/libhwsecurec


ccflags-y += -Idrivers/hisi/ddrc

ccflags-y += -Idrivers/hisi/ap/platform/kirin710

ccflags-y += -Idrivers/hisi/tzdriver/libhwsecurec
