# GOODIX 
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_ts.o 
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_gt9xx_update.o
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_ts_test.o
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_ts_tools.o
obj-$(CONFIG_GOODIX_TS_KIT) += goodix_dts.o
ccflags-y += -Idrivers/devkit/tpkit

ccflags-y += -Idrivers/devkit/tpkit/panel/goodix
